name: CI
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run shell script
      run: ./test.sh
      env:
        PASSWORD: ${{ secrets.PASSWORD }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: output
        path: output.txt